### ISSUE TITLE
how to update historical unencrypted data

### ISSUE THREAD

**Issue by saulomaximo** [alpaca-tc/active_record_encryption#33]
Hello,

I'm currently using Ruby 2.5.9 and Rails 5.2. I'm facing difficulties updating historical records using the model, especially after set to encrypt a specific attribute.

The scenario involves a table with existing historical data where a decision was made to encrypt a particular attribute. After configuring the model, new objects are successfully created with the attribute encrypted. However, I encounter issues when attempting to load or update old records. Specifically, I'm receiving the error message ActiveSupport::MessageVerifier::InvalidSignature.

Could someone advise on how to update the historical data and ensure the attribute is encrypted properly?

**Comment by alpaca-tc** [comment]
ActiveSupport has changed its default encryption method. 
If a column is encrypted using an older method, it may not be decryptable by the new method. 
While I don't have all the details to provide a comprehensive fix, here are some related changes and a simple solution that might help:

### https://github.com/rails/rails/pull/29263

```
# Use old cipher `cipher: 'aes-256-cbc'`
encrypted_attribute(:name, :field, encryption: { encryptor: :active_support, key: ENV['ENCRYPTION_KEY'], salt: ENV['ENCRYPTION_SALT'], cipher: 'aes-256-cbc' })
```

### https://github.com/rails/rails/pull/41043

```
# Use old hash_digest_class
Rails.application.config.active_support.hash_digest_class = OpenSSL::Digest::SHA1
```

**Comment by alpaca-tc** [comment]
Oops, were you talking about encrypting existing columns?
If you want to encrypt an existing column, the simplest way would be to add a new column for encryption and migrate the existing data to the new column.

**Comment by saulomaximo** [comment]
Thank you for the explanation.
